spring:
  application:
    name: product-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/rd-product-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect